version: "3.8"

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: plutomi
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql




volumes:
  mysql_data:
    driver: local
