plutomi:
  component: "@sls-next/serverless-component@3.3.0"
  inputs:
    name: # This should be set as the component will create hundreds of lambdas
      defaultLambda: ${env.DEFAULT_LAMBDA_NAME}
      apiLambda: ${env.API_LAMBDA_NAME}
      imageLambda: ${env.IMAGE_LAMBDA_NAME}

    roleArn: ${env.LAMBDA_ROLE_ARN}

    memory:
      defaultLambda: 256
      apiLambda: 256
      imageLambda: 1512
    domain: ${env.DOMAIN_NAME}
    bucketName: ${env.WEBSITE_BUCKET_NAME}

    # This must be set or we get downtime on subsequent deploys :(
    # You will have to deploy once to get your first ID
    cloudfront:
      distributionId: ${env.CLOUDFRONT_ID}

      # APP RUNNER SPECIFIC
      # This forwards our api requests to app runner
      # Lambda@Edge too expensive at more than a few million req / month :(
      # origins:
      #   - url: ${env.APP_RUNNER_URL}
      #     pathPatterns:
      #       # You might receive an error trying to deploy with 'api/*' for the first time
      #       # This is due to the duplicate Lambda api behavior pattern on cloudfront
      #       # If so, deploy with '/api/*' first and then redeploy with 'api/*'
      #       api/*:
      #         # Don't cache
      #         minTTL: 0
      #         maxTTL: 0
      #         defaultTTL: 0
