---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgA+6C56hHQyAjvf+rLTAxaMEZPdcpXReq3Hmp5nTtRuJR/wb5p1b+o5/vuaVeU1ofHnnlqUEy21oCqwSG4YzXNfZL4SMZh8e8OVy0mabMtruhYXKiwBsDkm/fP1CpcqCWAvM+psGQLTvLcoK4YzQVOlo9gM7KbQmaXBRJQZPKiBGL1pRcYNjtA8Vnc80zUCYPc/bE+ljRoNk4F7rjMwPkCQ3wVMaRxuJeI0QFwqvcrCldHRvPAHNeJQUnfuwCZaBHkPDKuF3NIQrfugMEJ6XNdfGXAfOlEozR8y4BaCKIwsNBnCW/SXTGO/YJA6AeZC5s9CH8T3MNj49Cm95c0uV7pyjtvGmAVaW/IcyIu9pAMByazgRddJok3vpro5f6g/1qsJnpW+YGCGtlw7rRkiAz8dzKp6db+y/OjCBJxt9I9AoirRyvADXkrz8RteFrzz3ES3kMYqsqHeYdeUOOK794K+gEvRKLbncHKax/e3Xk3+SA89NPOw12AHVm+4us8i4NWSVPnTScwAZBgTZ0u85dVhCxn0tbDwmQwiH8Ij+dezTn6XUAP28oHvWiiNfJglbsH4y8sAowKSm1VBdtwXb7gyovj0uSn8ZChaqaEWgKj0YYyElGCWzjkWqxzMJ5HKq/0y5ww/gsUe1U43aOzV8pDHK96PUOjPXr8CBe1aix19rzIjF+m7gg44n/od2hgH0hpznvFRR86SFsVqDrtD5jaZfYt7yrzK3hY6QQUeASOcieyyWySDm10C
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
