---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_DNS_TOKEN: TODO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
