---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCTmqKbYDCXXuLr65SQgGPkqLGN2zJgDyjs7ypDaiHekYaF9xT7x1GAazer/oPAbbDPAokLZhthlm8xsb/4xtq141u9F1o0NLdggS52cVB3m855ZbOv/v5CxZ7OjVak2Kzsbq1lYka6zOO30AeSDl0girmBh1cCXb/Iw5BJHRejDmZDFJt+PwqHO7YWeb7zvW0Uf1mamDOJfQcEpWT2uPLgKTYB3WxiaZ/bjhBggDTLMuCewEC7ohYq7Bu/KoKrfB+ZRH4jPKEcyQHET+Pn9ZJMjQzMoblaMRNeooryGz40EMyyvSsqgOueWzKw6EXj8dqhVhTjXBDYgfPtR9kWGqNVZp+8rWIW75+lrtK3NcJ7lQvfhyjaGQy3UhIWeu82qs+B7aZWQP7zlRpUohjEIqWBLAZZFEEE4dIT95q+IyEX7SlXXc4/tIr8sq/fPr3ppIK+SygvdG59M3VlqnLXTPVqvzt8cVG/p8SQ7ooP7us+bpnjgIshYIKHOWZjiSNJMratygeaXZngNNP7B/L4/scSzyqUk5/cvw6w/zHyOLdBJ1MVF2sqyp/F5tBy7PgwtqN46Erb3QPu1g+/9aOtnbcYn2lMGXJxp4Da+8JI68yTXhK3N1FtHIKKu18OLlXUI8UMAgAC8uZxK9b2Ngtb35g2sxQjPJncB06MC56TK3WvmfADKHOQDQwHjpwWtlfC/WSgF3yzag+gqUk7Pak5oJwVlCjB41zHMdhAww9GsTtDKinzP1lZFe04
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
