service:
  metadata:
    name: kafka-ui
  spec:
    selector:
      app: kafka-ui
    ports:
      - port: 8080
        targetPort: 8080

deployment:
  metadata:
    name: kafka-ui
    annotations:
      config.linkerd.io/skip-outbound-ports: "9092"
  spec:
    replicas: 1
    template:
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: kafka-ui
            image: provectuslabs/kafka-ui:latest
            port: 8080
            resources:
              requests:
                cpu: "100m"    # Reduce this as needed
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
            env:
              # TODO: add more nodes :D
              KAFKA_CLUSTERS_0_NAME: 
                value: "local"
              KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:
                value: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
              KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL:
                value: "PLAINTEXT"

            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 10
            lifecycle:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 10"]
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
