# https://artifacthub.io/packages/helm/nats/nats
service:
  merge:
    metadata:
      name: nats
    spec:
      selector:
        app: nats

config:
  cluster:
    enabled: false
    replicas: 1
  jetstream:
    enabled: true
    fileStore:
      dir: "/data/nats"
      pvc:
        size: 20Gi
  

container:
  resources:
    # Overriding defaults
    requests: {}
    limits: {}
  image:
    tag: 2.9.25

service:
  merge:
    metadata:
      name: nats
      annotations:
        # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
        # https://linkerd.io/2.15/features/protocol-detection/
        config.linkerd.io/opaque-ports: "4222"
    spec:
      selector:
        app: nats

statefulSet:
  merge:
    metadata:
      name: nats
    spec:
      selector:
        matchLabels:
          app: nats
      template:
        metadata:
          annotations:
            # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
            # https://linkerd.io/2.15/features/protocol-detection/
            config.linkerd.io/opaque-ports: "4222" 
          labels:
            app: nats
