# https://artifacthub.io/packages/helm/nats/nats
service:
  merge:
    metadata:
      name: nats
    spec:
      selector:
        app: nats

config:
  cluster:
    enabled: false
    replicas: 1
  jetstream:
    enabled: true
    fileStore:
      dir: "/data/nats"
      pvc:
        size: 20Gi
  

container:
  resources:
  # Overriding defaults
    requests: {}
    limits: {}
  image:
    tag: 2.9.25

service:
  merge:
    metadata:
      annotations:
        config.linkerd.io/opaque-ports: "4222"
        linkerd.io/inject: "enabled"

statefulSet:
  merge:
    metadata:
      name: nats
      # annotations:
      #   # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
      #   # https://linkerd.io/2.15/features/protocol-detection/
      #   config.linkerd.io/opaque-ports: "4222" # TODO: This should be removed!
      #   linkerd.io/inject: "enabled"  
    spec:
      selector:
        matchLabels:
          app: nats
      template:
        metadata:
          annotations:
            config.linkerd.io/opaque-ports: "4222" 
            linkerd.io/inject: "enabled"  
          labels:
            app: nats
# podTemplate:
#   merge:
#     metadata:
#       annotations:
#         # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
#         # https://linkerd.io/2.15/features/protocol-detection/
#         config.linkerd.io/opaque-ports: "4222"
#         linkerd.io/inject: "enabled"

# natsBox:
#   deployment:
#     merge:
#       metadata:
#         name: nats-box
#         labels:
#           app: nats-box
#         annotations:
#           # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
#           # https://linkerd.io/2.15/features/protocol-detection/
#           config.linkerd.io/opaque-ports: "4222"
#           linkerd.io/inject: "enabled"
#       spec:
#         selector:
#           matchLabels:
#             app: nats-box
#         template:
#           annotations:
#             # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
#             # https://linkerd.io/2.15/features/protocol-detection/
#             config.linkerd.io/opaque-ports: "4222"
#             linkerd.io/inject: "enabled"
#           metadata:
#             labels:
#               app: nats-box

  # podTemplate:
  #   merge:
  #     metadata:
  #       annotations:

