# https://artifacthub.io/packages/helm/nats/nats
service:
  merge:
    metadata:
      name: nats
    spec:
      selector:
        app: nats

config:
  cluster:
    enabled: false
    replicas: 1
  jetstream:
    enabled: true
    fileStore:
      dir: "/data/nats"
      pvc:
        size: 20Gi
  

container:
  resources:
  # Overriding defaults
    requests: {}
    limits: {}
  image:
    tag: 2.9.25

statefulSet:
  merge:
    metadata:
      annotations:
        # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
        # https://linkerd.io/2.15/features/protocol-detection/
        config.linkerd.io/opaque-ports: "4222,8222,6222" 


natsBox:
  deployment:
    merge:
      metadata:
        annotations:
          # https://github.com/linkerd/linkerd2/issues/1715#issuecomment-760311524
          # https://linkerd.io/2.15/features/protocol-detection/
          config.linkerd.io/opaque-ports: "4222,8222,6222" 
