# Default values
shared:
  env:
    ENVIRONMENT:
      value: development
    BASE_WEB_URL:
      value: https://plutomi.com
    KAFKA_BROKERS_URL:
      value: "kafka-kafka-bootstrap.default.svc.cluster.local:9092"
