service:
  metadata:
    name: web
  spec:
    # clusterIP: None
    selector:
      app: web
    ports:
      - port: 80
        targetPort: 3000

deployment:
  metadata:
    name: web

  spec:
    replicas: 2
    template:
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: web
            image: plutomi/web:latest
            port: 3000
            env:
              BASE_WEB_URL:
                value: https://plutomi.com
              ENVIRONMENT:
                value: development
            readinessProbe:
              periodSeconds: 10
              initialDelaySeconds: 10
              httpGet:
                path: /health
            lifecycle:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 10"]
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
