service:
  metadata:
    name: web
  spec:
    # clusterIP: None
    selector:
      app: web
    ports:
      - port: 80
        targetPort: 3000

deployment:
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: web
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: web
            image: plutomi/web:latest
            port: 3000
            resources:
              requests:
                cpu: "20m"
                memory: "128Mi"
            env:
            readinessProbe:
              periodSeconds: 10
              initialDelaySeconds: 10
              httpGet:
                path: /health
            lifecycle:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 10"]
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
