[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1.34.0", features = ["full"] }
base-encode = "0.3.1"
byteorder = "1.5.0"
getrandom = "0.2.11"
time = "0.3.30"
rand = "0.8.5"
serde = "1.0.192"
base62 = "2.0.2"
