[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-http = { version = "0.5.0", features = ["full"] }
axum = "0.7.2"
tokio = { version = "1.34.0", features = ["full"] }
rand = "0.8.5"
mongodb = "2.1"
dotenv = "0.15.0"
serde_json = "1.0.108"
futures = "0.3.29"
serde = "1.0.193"
tracing-axiom = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
