[package]
name = "plutomi-events"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "0.12.0", default-features = false, features = [
    "sqs",
] }

lambda_runtime = "0.8.3"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
] }
