[package]
name = "migrator"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
# Shared utils
shared = { path = "../shared" }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "tls-native-tls", "mysql" ] }
time = "0.3.36"
tokio = "1.40.0"
