apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ default 0 $.Values.overrides.maxUnavailable  }}
      maxSurge: {{ default 0 $.Values.overrides.maxSurge }}
  template:
    metadata:
      # # Disabled for now. Was using too many resources for my little cluster :3
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "9100"
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      terminationGracePeriodSeconds: {{ default 10 $.Values.overrides.terminationGracePeriodSeconds }}
      containers:
        {{- range .Values.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          ports:
            # - name: metrics
            #   containerPort: {{ .port }}
            - name: http
              containerPort: {{ .port }}
          env:
            - name: ENVIRONMENT
              value: {{ default "development" $.Values.overrides.ENVIRONMENT }}
            - name: BASE_WEB_URL
              value: {{ default "https://plutomi.com" $.Values.overrides.BASE_WEB_URL }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              {{- if $value.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name }}
                  key: {{ $value.secretKeyRef.key }}
              {{- else if $value.value }}
              value: {{ $value.value | quote }}
              {{- end }}
            {{- end }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ default 10 $.Values.overrides.preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ default "/health" $.Values.overrides.healthCheckPath }}
              port: {{ .port }}
            initialDelaySeconds: {{ default 10 $.Values.overrides.initialDelaySeconds }}
            periodSeconds: {{ default 10 $.Values.overrides.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
        {{- end }}
      volumes:
        {{- range .Values.spec.template.spec.volumes }}
        - name: {{ .name }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
