{{- if .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.name }}
  labels:
    app: {{ .Values.deployments.name }}
spec:
  replicas: {{ .Values.deployments.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployments.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployments.maxUnavailable }}
      maxSurge: {{ .Values.deployments.maxSurge }}
  template:
    metadata:
      # Disabled for now. Was using too many resources for my little cluster :3
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "9100"
      labels:
        app: {{ .Values.deployments.name }}
    spec:
      terminationGracePeriodSeconds: {{ $.Values.common.terminationGracePeriodSeconds }}
      containers:
        {{- range .Values.deployments.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            # - name: metrics
            #   containerPort: {{ .port }}
            - name: http
              containerPort: {{ .port }}
          env:
            - name: ENVIRONMENT
              value: {{ default "development" $.Values.deployments.ENVIRONMENT }}
            - name: BASE_WEB_URL
              value: {{ default "http://web.svc.default.local" $.Values.deployments.BASE_WEB_URL }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              {{- if $value.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name }}
                  key: {{ $value.secretKeyRef.key }}
              {{- else if $value.value }}
              value: {{ $value.value | quote }}
              {{- end }}
            {{- end }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ $.Values.deployments.preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ $.Values.deployments.healthCheckPath }}
              port: {{ .port }}
            initialDelaySeconds: {{ $.Values.deployments.initialDelaySeconds }}
            periodSeconds: {{ $.Values.deployments.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
        {{- end }}
      volumes:
        {{- range .Values.deployments.volumes }}
        - name: {{ .name }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
{{- end }}
