apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  clusterIP: {{ .Values.spec.clusterIP }}
  selector:
    app: {{ .Values.spec.selector.name }}
  ports:
    {{- range .Values.spec.ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
