apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  clusterIP: {{ .Values.spec.clusterIP }}
  selector:
    app: {{ .Values.metadata.name }}
  ports:
    - protocol: TCP
      # Port the pod listens on - global value from shared.yaml
      port: {{ .Values.spec.ports.port }}
      # Port that the service is exposed on
      targetPort: {{ .Values.spec.ports.port }}
