# Must start with 'deployments' key
deployments:
  replicas: 3
  name: api
  containers:
    - name: api
      port: 8080
      # TODO: xBuild for both x86 and ARM. Using x86 for now due to no ARM in US on Hetzner
      image: plutomi/api:latest 
      env:
        DATABASE_URL:
          secretKeyRef:
            name: global-config-secret
            key: DATABASE_URL
