# Must start with 'deployments' key
deployments:
  replicas: 3
  name: api
  containers:
    - name: api
      port: 8080
      # TODO update to ARM when available. Currently using x86
      image: plutomi/api:latest 
      env:
        DATABASE_URL:
          secretKeyRef:
            name: global-config-secret
            key: DATABASE_URL
