# Use this to override any values in the templates/deployment.yaml file
# This only applies to values that have '(index $.Values' setup
overrides: {}

deployment:
  metadata:
    name: web

  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: web
            image: plutomi/api:2024-06-21-v1
            port: 3000
