name: Deploy Website

# Only trigger, when the test workflow succeeded
# https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
on:
  workflow_run:
    workflows: ["Run Jest Tests"]
    branches: [master]
    types:
      - completed
  # push:
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: # TODO YUCK!!! There has to be a better way for this lol
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      WEBSITE_BUCKET_NAME: ${{ secrets.WEBSITE_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
      DEFAULT_LAMBDA_NAME: ${{ secrets.DEFAULT_LAMBDA_NAME }}
      API_LAMBDA_NAME: ${{ secrets.API_LAMBDA_NAME }}
      IMAGE_LAMBDA_NAME: ${{ secrets.IMAGE_LAMBDA_NAME }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      ID_LENGTH: ${{ secrets.ID_LENGTH }}
      DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
      GSI1_INDEX: ${{ secrets.GSI1_INDEX }}
      GSI2_INDEX: ${{ secrets.GSI2_INDEX }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Turnstyle # Actions concurrency limit
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Installing dependencies
        run: npm i

      - name: Deploying...
        run: npm run deploy
